name: Build and Deploy Frontend to Testing

on:
  pull_request:
    types:
      - closed

jobs:
  build-and-deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: |
          rm package-lock.json
          npm install

      - name: Build Frontend
        run: npm run build

      - name: Copy Files to Backend
        run: |
          mkdir -p backend/public
          cp -r frontend/dist/* backend/public/

      - name: Commit Changes to Testing
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git checkout -b testing
          git merge --no-ff ${{ github.event.pull_request.head.ref }} -m "ci: Merge branch '${{ github.event.pull_request.head.ref }}' into testing"
          git push
